name: kno
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - ipykernel
  - pandas
  - numpy
  - gunicorn
  - requests
  - pip:
    - fastapi
    - "uvicorn[standard]"
    - certifi
